In [ ]:
#Arithmatic operator
#comparison operator
#logical operator


In [ ]:
##addition and subtraction

In [1]:
a=15
b=8

In [2]:
a+b

23

In [3]:
a*b

120

In [4]:
a/b

1.875

In [5]:
2**3

8

In [6]:
##floor division
a//b

1

In [7]:
a%b

7

In [ ]:
// gives u quotient and % gives remainder of division

In [8]:
##comparison operator
a==b

False

In [9]:
a!=b

True

In [10]:
a==21

False

In [11]:
type(a==b)

bool

In [12]:
a>b

True

In [13]:
a<b

False

In [14]:
a>80

False

In [ ]:
#logical operator

In [15]:
(1==1)and (2==2)

True

In [16]:
(1==1) or (2==2)

True

In [17]:
if (2==2):
    print("TRUE statement")

TRUE statement


In [18]:
# if statement
x=1

if (x==1):
    print('TRUE')

TRUE


In [19]:
a=10
b=20

if (a>b):
    print("a is greater than b")
else:
    print("b is greater than a")

b is greater than a


In [20]:
##take input from user
x=input()

##by default type is string 
x=int(x)

if ((x%2)==0):
    print("even")
else:
    print("add")

50
even


In [22]:
##take input from user
y=input()

##by default type is string 
y=int(x)

if (y>90):
    print("Grade A")
elif(y>70):
    print("Grade B")
else:
    print("Grade C")

50
Grade C


In [ ]:
30th july

In [ ]:
##condition to repeat several times

In [1]:
for i in range(500):
    print("python is good")

python is good
python is good
python is good
python is good
python is good
python is good
python is good
python is good
python is good
python is good
python is good
python is good
python is good
python is good
python is good
python is good
python is good
python is good
python is good
python is good
python is good
python is good
python is good
python is good
python is good
python is good
python is good
python is good
python is good
python is good
python is good
python is good
python is good
python is good
python is good
python is good
python is good
python is good
python is good
python is good
python is good
python is good
python is good
python is good
python is good
python is good
python is good
python is good
python is good
python is good
python is good
python is good
python is good
python is good
python is good
python is good
python is good
python is good
python is good
python is good
python is good
python is good
python is good
python is good
python is good
python is good
python is 

In [3]:
for no in range(11):
    print(no)

0
1
2
3
4
5
6
7
8
9
10


In [4]:
for no in range(1,15):
    print(no)

1
2
3
4
5
6
7
8
9
10
11
12
13
14


In [5]:
for no in range(2,11,2):
    print(no)

2
4
6
8
10


In [6]:
for character in "sp clg":
    print(character)

s
p
 
c
l
g


In [ ]:
##nested for loops

In [8]:
for outer_loop_no in range(1,3):
    for inner_loop_no in "abc":
        print(outer_loop_no,inner_loop_no)

1 a
1 b
1 c
2 a
2 b
2 c


In [9]:
n=0
while(n<10):
    print(n)
    n=n+1

0
1
2
3
4
5
6
7
8
9


In [ ]:
##list

In [10]:
list=[1,2,3,4,5,6,7,8,9]

In [11]:
list

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [12]:
list[0]   ##to access particular element forom the list

1

In [14]:
list[-4]

6

In [ ]:
##slicing

In [15]:
list[::2]

[1, 3, 5, 7, 9]

In [16]:
list[2:5:1]

[3, 4, 5]

In [17]:
list[2:-2]

[3, 4, 5, 6, 7]

In [18]:
list[::1]

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [19]:
list[::]

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [ ]:
##appending

In [20]:
list.append(10)

In [21]:
list

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [22]:
list.append([15,16])

In [23]:
list

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, [15, 16]]

In [ ]:
##deleting

In [24]:
list.remove(5)

In [25]:
list

[1, 2, 3, 4, 6, 7, 8, 9, 10, [15, 16]]

In [26]:
del list[9]

In [27]:
list

[1, 2, 3, 4, 6, 7, 8, 9, 10]

In [28]:
list.extend([11,12,13,14])

In [29]:
list

[1, 2, 3, 4, 6, 7, 8, 9, 10, 11, 12, 13, 14]

In [30]:
list.index(14)

12

In [31]:
100 in list

False

In [32]:
15 in list

False

In [ ]:
##iterate

In [34]:
for element in list:
    print(element)

1
2
3
4
6
7
8
9
10
11
12
13
14


In [35]:
len(list)

13

In [36]:
list.reverse()

In [37]:
list

[14, 13, 12, 11, 10, 9, 8, 7, 6, 4, 3, 2, 1]

In [38]:
list.sort()

In [39]:
list

[1, 2, 3, 4, 6, 7, 8, 9, 10, 11, 12, 13, 14]

In [ ]:
passwd='2222'

for trial in range(1,5):
    if trial==4:
        print('one trial left!!')
    
    

In [ ]:
##EXAMPLE

In [ ]:
student_mark=[['Name',['A','B','C','D','E']]
             ]

In [ ]:
date:2nd july 2022

In [ ]:
#tuple

In [1]:
tuple=('A','B','C','D','D','E','F')

In [2]:
tuple[1]

'B'

In [3]:
tuple.index('E')

5

In [4]:
tuple.count('D')

2

In [6]:
for element in tuple:
 print(element)

A
B
C
D
D
E
F


In [9]:
tuple[:2]

('A', 'B')

In [10]:
tuple[3:5].count('D')

2

In [11]:
tuple.index('B')

1

In [ ]:
##tuple is immutable

In [12]:
del tuple[1]

TypeError: 'tuple' object doesn't support item deletion

In [ ]:
##set

In [24]:
set1={'A','B','C','D',1,2,4}

In [25]:
set1

{1, 2, 4, 'A', 'B', 'C', 'D'}

In [26]:
#defining a set from a list and tiple

In [29]:
list1=['A','B',1,2,6]
myset=set(list1)

TypeError: 'set' object is not callable

In [30]:
set1.add('p')

In [31]:
set1

{1, 2, 4, 'A', 'B', 'C', 'D', 'p'}

In [32]:
set1.discard('A')

In [33]:
set1

{1, 2, 4, 'B', 'C', 'D', 'p'}

In [34]:
set1.remove(1)

In [35]:
set1

{2, 4, 'B', 'C', 'D', 'p'}

In [ ]:
#difference between two sets

In [ ]:
set1.diffrence

In [39]:
set1={'a','b','c','d'}
set2={'a','d','e'}


In [40]:
set1.union(set2)

{'a', 'b', 'c', 'd', 'e'}

In [41]:
set1.add('s')

In [42]:
set1

{'a', 'b', 'c', 'd', 's'}

In [ ]:
#dictionary

In [45]:
dict1={'anjali':[150,46],'shital':[146,58],'disha':[160,50]}

In [46]:
dict1

{'anjali': [150, 46], 'shital': [146, 58], 'disha': [160, 50]}

In [47]:
dict1.update({'rakesh':[146,50]})

In [48]:
dict1

{'anjali': [150, 46],
 'shital': [146, 58],
 'disha': [160, 50],
 'rakesh': [146, 50]}

In [50]:
dict2={'name':['anjali','rahul','rakesh'],
      'age':[21,23,25],
      'rollno':[10,25,35]
      }

In [51]:
dict2

{'name': ['anjali', 'rahul', 'rakesh'],
 'age': [21, 23, 25],
 'rollno': [10, 25, 35]}

In [54]:
dict1.keys()

dict_keys(['anjali', 'shital', 'disha', 'rakesh'])

In [55]:
dict1.values()

dict_values([[150, 46], [146, 58], [160, 50], [146, 50]])

In [56]:
dict1.update({'appu':[126,25]})

In [57]:
dict1

{'anjali': [150, 46],
 'shital': [146, 58],
 'disha': [160, 50],
 'rakesh': [146, 50],
 'appu': [126, 25]}

In [ ]:
#duplicate keys

In [59]:
sample={'A':1,
       'B':2,
       'C':3,'A':100}

In [60]:
sample


{'A': 100, 'B': 2, 'C': 3}

In [61]:
dict1==dict2

False

In [62]:
for key,value in dict1:
    print(key)

ValueError: too many values to unpack (expected 2)

In [ ]:
#strings

In [64]:
s='anjali'

In [65]:
len(s)

6

In [66]:
s[0]

'a'

In [68]:
s[4]

'l'

In [69]:
s[-1]

'i'

In [ ]:
#slicing

In [70]:
s[1:3]

'nj'

In [71]:
s[-5:5]

'njal'

In [72]:
s[::-1]

'ilajna'

In [73]:
s.count('a')

2

In [74]:
s.find('a')

0

In [75]:
s.index('j')

2

In [77]:
s.startswith('i')

False

In [78]:
s.endswith('i')

True

In [79]:
s.islower()

True

In [80]:
s.isupper()

False

In [81]:
s.isnumeric()

False

In [82]:
'java is easy to learn'.replace('java','python')

'python is easy to learn'

In [83]:
'python is easy to learn'.split(' ')

['python', 'is', 'easy', 'to', 'learn']

In [ ]:
4 july lec

In [6]:
##with return
def no():
    total=3+6
    print('sum is:',total)
    return total

In [7]:
op1=no()

sum is: 9


In [10]:
op1 ##value get stored when return is used

9

In [11]:
#without return
def no():
    total=3+6
    print('sum is:',total)

In [12]:
op2=no()

sum is: 9


In [13]:
op2  ##value is not returned

In [14]:
def welcome(name):
    return 'welcome, '+ name

In [16]:
welcome('anjali')

'welcome, anjali'

In [17]:
##default value
def welcome(name= 'anjali'):
    return 'welcome, '+ name

In [18]:
welcome()

'welcome, anjali'

In [21]:
##positional argument
def math(small_no,large_no):
    diff=large_no- small_no
    return diff

In [22]:
math(5,16)

11

In [23]:
math(16,5)

-11

In [24]:
##keyword argument
def math(small_no=16,large_no=60):
    diff=large_no- small_no
    return diff

In [25]:
math()

44

In [ ]:
##in python we always define arguments before the keyword argument

In [ ]:
##variable length argument

In [30]:
def my_function(*args):
    for i in args:
        print(i)

In [31]:
my_function(1,23,4,5)

1
23
4
5


In [ ]:
##when keyword is not used we use * or we do not know how many arg

In [33]:
my_function(1,'anj','true')

1
anj
true


In [34]:
def my_function(**kwargs):
    for key,value in kwargs.items():
        print(key,value)
        ##use ** when key value is used

In [35]:
my_function(a=10,b=10,c=45,d=46)

a 10
b 10
c 45
d 46


In [ ]:
##local and global variable

In [36]:
name='variable outside func'
def func():
    return name

In [38]:
func()

'variable outside func'

In [41]:
name='variable outside func'
def func():
    name='variable inside func'
    return name

In [46]:
func()


'variable inside func'

In [45]:
print(name)

variable outside func


In [47]:
name='variable outside func'
def func():
    global name
    name='variable inside func'
    return name

In [48]:
func()

'variable inside func'

In [49]:
name

'variable inside func'

In [ ]:
##we are reassigning global variable by global keyword

In [ ]:
##lambda function

In [51]:
def add(a):
    return a+20

In [52]:
add(30)

50

In [54]:
var=lambda a : a+20
print('with argument value 5:',var(5))

with argument value 5: 25


In [ ]:
##lambda with two argument 

In [59]:
original_list = [1,2,3,4,5]
filtered_list=list(filter(lambda x:(x%2 !=0),list)) 
print('multiple of 5:',filtered_list)

TypeError: 'list' object is not callable

In [ ]:
##reduce function


In [60]:
def count_handshake(total):
    count=0
    for i in range(1,total):
        print('handshake of ',i 'and',j)

SyntaxError: invalid syntax (<ipython-input-60-349ac8ee75bb>, line 4)

In [ ]:
7 july

In [1]:
import math

In [2]:
math.ceil(20.222)  ##give smallest integer greater than or equal to x

21

In [5]:
math.floor(20.222)

20

In [3]:
math.factorial(10)

3628800

In [4]:
math.gcd(20,25)

5

In [ ]:
##random

In [7]:
import random

In [9]:
random.choice(['apple','pear','banana'])

'banana'

In [10]:
random.random()

0.10822205034605592

In [11]:
random.uniform(0,2)

0.9378598913408593

In [12]:
random.randrange(1,10)

2

In [14]:
random.randint(1,10)

9

In [ ]:
##Date time

In [15]:
from datetime import date


In [17]:
today=date.today()  ##get current date
print('Date: ',today)

Date:  2022-08-07


In [19]:
##format date
print('formated date: ',today.strftime("%m-%d-%y."))

formated date:  08-07-22.


In [20]:
print('formated date: ',today.strftime("%d %b %Y"))

formated date:  07 Aug 2022


In [23]:
print('formated date: ',today.strftime("%A on the %d day of %B."))

formated date:  Sunday on the 07 day of August.


In [24]:
birthday=date(2000,5,15)
age=today-birthday
print('age in ')

In [25]:
age

datetime.timedelta(days=8119)

In [ ]:
##basics of numpy

In [27]:
import numpy as np

In [ ]:
#check version of numpy libraries

In [30]:
np._version_

AttributeError: module 'numpy' has no attribute '_version_'

In [31]:
np.array([1,2,3])

array([1, 2, 3])

In [33]:
np.array([1,2,3,False,'5'])  ##array take element of same type if another element used it convert in string format

array(['1', '2', '3', 'False', '5'], dtype='<U11')

In [34]:
#create a sample list
sample_list=[1,2,3,4,5,6]

In [35]:
sample_list*2

[1, 2, 3, 4, 5, 6, 1, 2, 3, 4, 5, 6]

In [36]:
#create sample numpy array
sample_numpy_array=np.array([1,2,3,4,5,6])

In [37]:
sample_numpy_array+2

array([3, 4, 5, 6, 7, 8])

In [38]:
sample_numpy_array*2

array([ 2,  4,  6,  8, 10, 12])

In [39]:
##create a matrix
a=[[1,2,3],[4,5,6],[7,8,9]]

In [40]:
a

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [41]:
a=np.array(a)

In [42]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [43]:
a[0][1]

2

In [44]:
b=np.array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [45]:
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [46]:
np.random.randint(0,10,(3,3))

array([[6, 1, 2],
       [4, 7, 1],
       [4, 1, 2]])

In [47]:
np.random.randint(0,10,(3,3)) #another matrix

array([[0, 1, 6],
       [3, 8, 2],
       [6, 7, 5]])

In [48]:
#fixing random seed  #same sample get created usind seed
np.random.seed(0)
np.random.randint(0,10,(3,3))

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2]])

In [49]:
#create matrix of zeros
np.zeros((4,5),dtype=int)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [50]:
#matrix of one
np.ones((4,5),dtype=int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [51]:
np.identity((5),dtype=int)

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [52]:
np.full((2,4),7)

array([[7, 7, 7, 7],
       [7, 7, 7, 7]])

In [53]:
#array concatination #joining
matrix1=np.array([[1,2,3],[4,5,6]])

In [54]:
print('matrix1')

matrix1


In [55]:
matrix1

array([[1, 2, 3],
       [4, 5, 6]])

In [56]:
matrix2=np.array([[7,8,9],[10,11,12]])
print('matrix2')
matrix2

matrix2


array([[ 7,  8,  9],
       [10, 11, 12]])

In [58]:
matrix3=np.concatenate([matrix1,matrix2],axis=0)
print('combined on row(axis=0)')
matrix3

combined on row(axis=0)


array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [60]:
##concatenate colm wise
matrix3=np.concatenate([matrix1,matrix2],axis=1)
print('combined on col(axis=1)')
matrix3

combined on col(axis=1)


array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])